openapi: 3.0.0

info:
  title: Basic API Example
  description: This is an example of how to create an openapi document for the server API
  version: 0.0.1

servers:
  - url: http://localhost:3333
    description: Local Development

paths:
  /note:
    post:
      tags:
        - Note
      summary: Create a new Notes
      description: Create a new note with a name
      requestBody:
        description: Note data to save to DB
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Single Note Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: 'TODO: name is empty or invalid'

  /note/{id}:
    get:
      tags:
        - Note
      summary: Return a note, specified by id
      description: Returns a single note only
      parameters:
        - name: id
          in: path
          required: true
          description: id of the Note to returns
          schema:
            type: integer
            example: 1
            minimum: 1
      responses:
        '200':
          description: Single note object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: 'specified id is invalid (not integer)'
        '404':
          description: 'Note with specified id is not available'
        '500':
          description: Unexpected Error


components:
  schemas:
    Note:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'todo: dishes'
      required:
        - id
        - name
